<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

        </div>

</header>
<div class="container">
<a href="/kphalcon/admin/changecredits/"><h4 class="glyphicon glyphicon-pencil">Verander gebruiker credits</h4></a></br>
<a href="/kphalcon/mediaplayer/videoactions/"><h4 class="glyphicon glyphicon-pencil">Verwijder Masterclasses</h4></a>
</br>
<a href="/kphalcon/mediaplayer/bronsvideo/"><h4 class="glyphicon glyphicon-pencil">Voeg een Masterclass toe</h4></a>
<a href="/kphalcon/mediaplayer/subvideo/"><h4 class="glyphicon glyphicon-pencil">Voeg een sub-Masterclass toe</h4></a>

<a href="/kphalcon/mediaplayer/addthumb/"><h4 class="glyphicon glyphicon-pencil">Voeg een videolink toe</h4></a>
</div>

