<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

        </div>

</header>

<?php
    $mediabrons = mediabrons::find("");

?>
<div class="container container-beta">
{% if auth['lvl'] == 6 %}

{{ form("mediaplayer/addthumb") }} 
{{ select("mediabrons", mediabrons, "using": ["media_id","titel"], "class": "form-control") }}
{{ text_field("videolink", "class": "form-control", "placeholder": "videolink : https://player.vimeo.com/video/voorbeeld")}}
 {{ submit_button("submit", "class": "inlogpos btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha") }}

{{ end_form() }}

{% endif %}
{{message}}
</div>
