<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

        </div>

</header>
{% if auth['lvl'] == 6 %}
<?php

?>

<div class="container">
<h1>Brons</h1>
{{ form("mediaplayer/bronsvideo") }}
{{ text_field("videos", "class": "form-control", "placeholder": "videolink : https://player.vimeo.com/video/voorbeeld")}}
{{ text_field("thumbnail", "class": "form-control", "placeholder": "Naam van thumbnail //Bijvoorbeeld: ondernemen") }}
{{ text_field("titel", "class": "form-control", "placeholder": "Titel hier")}}
{{ text_field("subtitel", "class": "form-control", "placeholder": "Sub-titel hier")}}
{{ text_area("description", "class": "tinymce form-control", "placeholder": "Video beschrijving hier")}}
{{numeric_field("credit_amount", "class": "form-control", "placeholder": "video kosten")}}
{{numeric_field("student_plaatsen", "class": "form-control", "placeholder": "aantal plaatsen voor studenten")}}
{{numeric_field("docent_plaatsen", "class": "form-control", "placeholder": "aantal plaatsen voor docenten")}}
{{numeric_field("ondernemer_plaatsen", "class": "form-control", "placeholder": "aantal plaatsen voor ondernemers")}}
{{ submit_button("submit", "class": "btn btn-primary") }}
{{ end_form() }}

<h5>Upload header hier</h5>
{{ form('mediaplayer/uploadheader','enctype':'multipart/form-data','method':'POST')}}
{{file_field('files[]')}}
{{submit_button('Upload Image', 'class':'btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha')}}
{{ end_form() }}
 

<h1>Upload thumbnail hier</h1>
{{ form('mediaplayer/upload','enctype':'multipart/form-data','method':'POST')}}
{{file_field('files[]', 'class':'form-control')}}
{{submit_button('Upload Image', 'class':'btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha')}}
{{ end_form() }}
 
</div>


{% endif %}
{{message}}