<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_young-creatives.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">Admin Dashboard:<br>{{auth['firstname']}} {{auth['lastname']}}</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

        </div>

</header>
{% if auth['lvl'] == 6 %}
<?php
    $mediabrons = mediabrons::find();
?>

<div class="container">
<h1>Brons</h1>
{{ form("mediaplayer/subvideo") }}
{{ select("mediabrons", mediabrons, "using": ["media_id","titel"], "class": "form-control") }}
{{ text_field("subvideos", "class": "form-control", "placeholder": "videolink : https://player.vimeo.com/video/voorbeeld")}}
{{ text_field("thumbnail", "class": "form-control", "placeholder": "Naam van thumbnail //Bijvoorbeeld: ondernemen") }}
{{ text_field("titel", "class": "form-control", "placeholder": "Titel hier")}}
{{ submit_button("submit", "class": "btn btn-primary") }}
{{ end_form() }}

<h1>Upload thumbnail hier</h1>
{{ form('mediaplayer/upload','enctype':'multipart/form-data','method':'POST')}}
{{file_field('files[]', 'class':'form-control')}}
{{submit_button('Upload Image', 'class':'btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha')}}
{{ end_form() }}
 
</div>


{% endif %}
{{message}}