<header id="header" class="header" data-extension="Contact" style="background-image: url('http://kweekvijvernoord.com/wp-content/uploads/2017/04/Kweekvijver_stage.jpg');">

	
      

 <div class="container header__container">

            
            <div class="header__inner header__inner--large">

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/top-line-header-title.png">

                </div>

                <h1 class="header__title text-transform-uppercase">NEVER UNDERESTIMATE THE POWER OF THE YOUNG.</h1>

                <div class="header__responsive-line">

                    <img src="http://kweekvijvernoord.com/wp-content/themes/kvn/assets/img/bottom-line-header-title.png">

                </div>

            </div>

        </div>

    </header>
<div class="container">
    <h2>Tickets</h2>
    <div class="alignbody">
        <div class="alignpackage credits">
            {{ partial("credit/package1")}} 
            {{ content()}}
        </div>
        <div class="alignpackage credits">
            {{ partial("credit/package2")}}
        </div> 
        <div class="alignpackage credits"> 
            {{ partial("credit/package3")}} 
            {{ content()}}
        </div>
        <div class="alignpackage credits"> 
            {{ partial("credit/package4")}} 
            {{ content()}}
        </div> 
        <div class="alignpackage credits"> 
            {{ partial("credit/package5")}} 
            {{ content()}}
        </div>       
        
            
        

    </div>
<hr>    
</div>
<div class="container">
    <p class="text"><b>Koop hier uw tickets</b></p>
    <p class="text">Om bij een masterclass aanwezig te kunnen zijn hebt u een ticket nodig. Deze kunt u hier aanschaffen. Hoe meer tickets u aanschaft, des te goedkoper ze worden.</p>
    <hr>
    <p class="text"><b>Uw eigen account</b></p>
    <p class="text">Nadat u uw tickets hebt besteld via het ticketformulier krijgt u van ons per e-mail uw inloggegevens én de bijbehorende factuur. Deze factuur kent een betalingstermijn van 14 dagen. Maar u kunt zich via uw eigen account ook al direct aanmelden voor de gewenste masterclass(es) zodat u niets hoeft te missen.</p>
    <hr>
    <p class="text"><b>Deel uw tickets met wie u maar wilt</b></p>
    <p class="text">Wanneer u meer tickets ineens koopt, kunt u deze delen met iedereen met wie u maar wilt. Denk aan collega’s, vakgenoten of studenten. U kunt zich ook via uw eigen account met meerdere personen voor één masterclass aanmelden.</p>
    <hr>
    <p class="text"><b>Online content</b></p>
    <p class="text">Van alle masterclasses worden video-opnames gemaakt. Op die manier kunt u de presentaties van de (meeste) sprekers achteraf terugkijken. Ook vindt u allerlei extra content in de vorm van checklists, voorbeelden, tips, filmpjes en nog veel meer!</p>    
</div>
