<h2 class="creditpack1 creditpacks">1<br>Ticket</h2>
<h4 class="money">€150,-</h4>

<input type="submit" value="Koop Tickets" class="btn btn--ghost btn--epsilon btn--right-arrow btn--medium icon icon--right-open-1 icon--margin-alpha" data-fancybox data-src="#kooptickets1" href="javascript:;">

<div style="display: none;" id="kooptickets1">

	<div class="container container-beta">
		<h6>Weet je zeker dat je 1 ticket wil aanschaffen?</h6>
		<p>Om bij een masterclass aanwezig te kunnen zijn hebt u een ticket nodig. Deze kunt u hier aanschaffen. Hoe meer tickets u aanschaft, des te goedkoper ze worden.</p>
		{{ form("session/buycredit") }} 
		{{ text_field("credits", "value": "1", "style":"display:none")}}
		{{ submit_button("submit", "class": "btn btn-primary") }}
		{{ end_form() }}

	</div>

</div>		